### ISSUE TITLE
Does virtual-node deployment has to be hostnetwork?

### ISSUE THREAD

**Issue by lmxia** [virtual-kubelet/tensile-kube#81]
The deployment yaml of virtual node spec that the virtual-node pod network mode is: hostnetwork.

However if we join one more cluster, the port of KUBELET_PORT must be managed manually, so why use hostnetwork?

**Comment by cwdsuzhou** [comment]
> The deployment yaml of virtual node spec that the virtual-node pod network mode is: hostnetwork.
> 
> However if we join one more cluster, the port of KUBELET_PORT must be managed manually, so why use hostnetwork?

Not necessary.

1. Underlay  network, `hostNetwork` is not necessary directly.
2. Overlay network, if we should make api-server could access KUBELET_IP: KUBELET_PORT. 
 Take flannel network for example, we should also allocate an overlary ip for the node where api-servers run on, or add a LB for the vk pod. Otherwise, you should use `hostNetwork`.


All of these helps make `kubectl exec` and `kubectl logs` work.

**Comment by cwdsuzhou** [comment]
Close this issue. If you have any other question, you can open another issue.
